[libraries]
# AndroidX-included
androidx-room-runtime = { module = "androidx.room:room-runtime" }
androidx-room-ktx = { module = "androidx.room:room-ktx" }
androidx-room-compiler = { module = "androidx.room:room-compiler" }
androidx-arch-core-testing = { module = "androidx.arch.core:core-testing" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose" }
androidx-core = { group = "androidx.core", name = "core-ktx" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose" }
androidx-test-core = { module = "androidx.test:core" }
androidx-junit = { module = "androidx.test.ext:junit" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core" }
hilt-android = { module = "com.google.dagger:hilt-android" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler" }
hilt-testing = { module = "com.google.dagger:hilt-android-testing" }
retrofit-bom = { module = "com.squareup.retrofit2:retrofit-bom" }
retrofit = { module = "com.squareup.retrofit2:retrofit" }
retrofit-kotlinx-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test" }
kotlinx-immutable-collection = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable" }

# unit test
junit = { module = "junit:junit" }
mockito-core = { module = "org.mockito:mockito-core" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin" }
robolectric = { module = "org.robolectric:robolectric" }
truth = { module = "com.google.truth:truth" }
profileinstaller = { module = "androidx.profileinstaller:profileinstaller" }
macrobenchmark = { module = "androidx.benchmark:benchmark-macro-junit4" }
uiautomator = { module = "androidx.test.uiautomator:uiautomator" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json" }

[bundles]
retrofitBundle = ["retrofit", "retrofit-kotlinx-serialization", "okhttp-logging-interceptor"]
